.TH Ex0
.SH NAME
Ex0 \- Command Line
.SH SYNOPSIS
The goal of this Exercise was to help familiarize ourselves with some of the commands that we will 
use throughout the class
.SH DESCRIPTION
1. I created a folder using the command mkdir
.br .br
2. the command issued at this step is grep -nr '/usr/rep/src/reptilian-kernel/' -e 'android_dev'. The grep command is
used to search for a string within files in a directory. The option n is to display infornmation and r is to search 
every folder within the directory. 
.br .br
3. I reissued the same command from step 2 however I added " > " after and then specified what I wanted
to name the output file as
.br .br
5. I moved the file using the mv command
.br .br
6. Commands that were used other than the ones provided in File Packaging include touch: creating text file, gzip: 
used to gzip file, gunzip: used to unzip file
.br .br
7.I used the following command to zip the folder: tar -cvf ex1.tar /home/reptilian/rudra_rahul
.SH TESTING
Tested continuously mostly by checking the files in the current directory using the ls command
.SH BUGS
No Significant Issues were encountered. 
.SH LINK
N/A
.SH REFERENCES/CITATIONS
https://www.youtube.com/watch?v=VGgTmxXp7xQ
.br .br
https://www.tecmint.com/18-tar-command-examples-in-linux/
.br .br
All other commands used in this exercise I previously knew
.SH AUTHOR
Rahul Rudra
